services:
  - type: web
    name: messagerie-app
    runtime: go
    # On supprime le "cd server" et on corrige le chemin de sortie (-o app au lieu de -o ../app)
    buildCommand: go build -tags netgo -ldflags '-s -w' -o app
    startCommand: ./app
    envVars:
      - key: PORT
        value: 3000